// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICosmicAlign: typeof import('~icons/cosmic/align')['default']
    ICosmicArrowDown: typeof import('~icons/cosmic/arrow-down')['default']
    ICosmicArrowRight: typeof import('~icons/cosmic/arrow-right')['default']
    ICosmicBoard: typeof import('~icons/cosmic/board')['default']
    ICosmicCanvas: typeof import('~icons/cosmic/canvas')['default']
    ICosmicCaution: typeof import('~icons/cosmic/caution')['default']
    ICosmicDark: typeof import('~icons/cosmic/dark')['default']
    ICosmicSun: typeof import('~icons/cosmic/sun')['default']
  }
}

export { }
